# Name of website
title: Th!nk Pos!tive

# Name to show in the footer
author: Stefan Freitag

baseurl: "/home"
twitter_username: stefanfreitag
github_username:  stefanfreitag
theme: jekyll-theme-hacker
